name: book_box
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.0+7

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: "3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  intl: ^0.18.1
  horizontal_calendar:
    path: packages/horizontal_calendar
  flutter_native_splash: ^2.3.1
  syncfusion_flutter_sliders: ^23.2.7
  table_calendar: ^3.0.0
  flutter_inappwebview: ^6.0.0
  http: ^0.13.5
  shared_preferences: ^2.2.2
  flutter_typeahead: ^5.0.1

  geolocator: ^8.2.0
  geocoding: ^2.0.4
  phonepe_payment_sdk: ^2.0.1
  crypto: ^3.0.3

  change_app_package_name: ^1.1.0
  url_launcher: ^6.2.6
  go_router: ^14.1.3
  qr_flutter: ^4.0.0
  share_plus: ^6.3.1
  path_provider: ^2.0.14
  screenshot: ^3.0.0
  app_links: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Sofia Sans
      fonts:
        - asset: assets/fonts/SofiaSans-Regular.ttf
        - asset: assets/fonts/SofiaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SofiaSans-Bold.ttf
          weight: 700

flutter_native_splash:
  ios: false
  web: false

  # Will work bellow the Android 12
  background_image: assets/launch.png
  # image: assets/launch.png

  android_12:
    image: assets/launch.png
    # background_image: assets/launch.png
    color: "#277537"
    color_dark: "#277537"
  fullscreen: true
